pull_request_rules:
  - name: merge pull requests from dependabot if CI passes
    conditions:
      - author=dependabot-preview[bot]
      - status-success=FactionC2.Console
      - base=development
    actions:
      merge:
        method: merge
        strict: smart