apiVersion: v1
kind: ConfigMap
metadata:
    name: console-config-nginx
data:
    default.conf: |
        access_log                  /dev/stdout;
        error_log                   /dev/stdout debug;

        server {
            server_name                 localhost;
            listen                      80;
            root                        /usr/share/nginx/html;
            index                       index.html;
            error_page                  500 502 503 504  /50x.html;

            keepalive_timeout           3000;
            client_max_body_size        1g;

            proxy_connect_timeout       60s;
            proxy_read_timeout          1d;
            proxy_send_timeout          10m;
            gzip                        on;

            location / {
                add_header              X-Faction RocksSocks;
                try_files               $uri $uri/ =404;
            }
        }
