apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config-env
  labels:
    app: faction-console
data:
  VUE_APP_ROUTER_MODE: "history"
  VUE_APP_GRAPHQL_ENDPOINT: "/api/v1/graphql/"
  VUE_APP_AUTH_ENDPOINT: "/api/v1/auth/"
